# Generated by Django 2.0.5 on 2018-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_Code', models.IntegerField(choices=[(1, 'E9 Premium, #06-17'), (2, 'Hiangkie Industrial Building, #04-14'), (3, 'Mayfair Industrial Building, #05-30')], default=0)),
                ('Area_Code', models.IntegerField(default=0)),
                ('Image', models.CharField(default='', max_length=200)),
                ('Brand', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Herman Miller'), (2, 'Steelcase'), (3, 'Teknion'), (4, 'Haworth'), (5, 'Knoll'), (6, 'Wilkhahn'), (7, 'Benel'), (8, 'Fusys'), (9, 'Humanscale'), (10, 'Enjoy'), (11, 'Ergohuman'), (12, 'Artmatrix'), (13, 'X3'), (14, 'Unigroup')], default=0)),
                ('Color', models.IntegerField(choices=[(1, 'Maple'), (2, 'White'), (3, 'Grey'), (4, 'Cherry'), (5, 'Brown'), (6, 'Beech'), (7, 'Ivory'), (8, 'Black')], default=1)),
                ('Material', models.IntegerField(choices=[(1, 'Wooden'), (2, 'Metal')], default=1)),
                ('Design', models.IntegerField(choices=[(1, 'Swing Door - 2 Doors'), (2, 'Swing Door - 4 Doors'), (3, 'Drawer'), (4, 'Sliding Door - Fully Open'), (5, 'Sliding Door - Half Open'), (6, 'Open Shelf'), (7, 'Combination')], default=1)),
                ('Drawer', models.IntegerField(choices=[(1, 'No applicable'), (2, '2 Drawers'), (3, '3 Drawers'), (4, '4 Drawers')], default=1)),
                ('Height', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('Depth', models.IntegerField()),
                ('Leveling_Wheel', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1)),
                ('Handle', models.IntegerField(choices=[(1, 'With handle'), (2, 'No Handle')], default=1)),
                ('Mobility', models.IntegerField(choices=[(1, 'No wheels'), (2, '4 wheels'), (3, '5 wheels')], default=1)),
                ('Is_Faulty', models.BooleanField(default=False)),
                ('Description', models.TextField(default='', max_length=500)),
                ('Quantity_For_This_Entry', models.IntegerField()),
                ('Custom_Code', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Cabinets',
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_Code', models.IntegerField(choices=[(1, 'E9 Premium, #06-17'), (2, 'Hiangkie Industrial Building, #04-14'), (3, 'Mayfair Industrial Building, #05-30')], default=0)),
                ('Area_Code', models.IntegerField(default=0)),
                ('Image', models.CharField(default='', max_length=200)),
                ('Brand', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Herman Miller'), (2, 'Steelcase'), (3, 'Teknion'), (4, 'Haworth'), (5, 'Knoll'), (6, 'Wilkhahn'), (7, 'Benel'), (8, 'Fusys'), (9, 'Humanscale'), (10, 'Enjoy'), (11, 'Ergohuman'), (12, 'Artmatrix')], default=0)),
                ('Specific_Model', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Herman Miller Aeron'), (2, 'Vitra T Chair'), (3, 'Benel EE'), (4, 'Benel Freniq'), (5, 'Knoll Life'), (6, 'Haworth Look'), (7, 'Vitra Meda 2'), (8, 'Fusys Pion'), (9, 'Humanscale'), (10, 'Steelcase Leap V1'), (11, 'Steelcase Leap V2'), (12, 'Steelcase Sensor'), (13, 'Herman Miller Eames'), (14, 'Benel Q-Mesh'), (15, 'Steelcase Think 3D'), (16, 'Enjoy'), (17, 'Ergohuman'), (18, 'Herman Miller Mirra 2'), (19, 'Haworth Easy'), (20, 'Haworth Zody'), (21, 'Wilkhahn ON Task')], default='')),
                ('Back_Material', models.IntegerField(choices=[(1, 'Fabric'), (2, 'Mesh'), (3, 'Leather'), (4, 'Wooden')], default=0)),
                ('Back_Color', models.IntegerField(choices=[(1, 'Black'), (2, 'White'), (3, 'Grey'), (4, 'Red'), (5, 'Orange'), (6, 'Yellow'), (7, 'Green'), (8, 'Blue'), (9, 'Purple'), (10, 'Brown')], default=0)),
                ('Cushion_Material', models.IntegerField(choices=[(1, 'Fabric'), (2, 'Mesh'), (3, 'Leather'), (4, 'Wooden')], default=0)),
                ('Cushion_Color', models.IntegerField(choices=[(1, 'Black'), (2, 'White'), (3, 'Grey'), (4, 'Red'), (5, 'Orange'), (6, 'Yellow'), (7, 'Green'), (8, 'Blue'), (9, 'Purple'), (10, 'Brown')], default=0)),
                ('With_Lumbar_Support', models.BooleanField(default=False)),
                ('With_Recline', models.BooleanField(default=True)),
                ('With_MultiLock', models.BooleanField(default=False)),
                ('With_Seat_Depth_Adjustment', models.BooleanField(default=False)),
                ('With_Back_Height_Adjustment', models.BooleanField(default=False)),
                ('With_Headrest', models.BooleanField(default=False)),
                ('With_Gaslift_Adjustable', models.BooleanField(default=True)),
                ('Armrest_Height_Adjustment', models.BooleanField(default=False)),
                ('Armrest_Direction_Adjustment', models.BooleanField(default=False)),
                ('Leg_Material', models.IntegerField(choices=[(1, 'Metal or Alloy'), (2, 'Wooden'), (3, 'Nylon or plastic')], default=0)),
                ('Leg_Color', models.IntegerField(choices=[(1, 'Black'), (2, 'White'), (3, 'Grey'), (4, 'Red'), (5, 'Orange'), (6, 'Yellow'), (7, 'Green'), (8, 'Blue'), (9, 'Purple'), (10, 'Brown')], default=0)),
                ('Is_Faulty', models.BooleanField(default=False)),
                ('Faulty_Description', models.TextField(default='', max_length=500)),
                ('Quantity_For_This_Entry', models.IntegerField()),
                ('Custom_Code', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Chairs',
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('仓库', models.IntegerField(choices=[(1, 'E9 Premium, #06-17'), (2, 'Hiangkie Industrial Building, #04-14'), (3, 'Mayfair Industrial Building, #05-30')], default=0)),
                ('区号', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40')], default=1)),
                ('照片', models.CharField(blank=True, default='', max_length=200)),
                ('品牌', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Herman Miller'), (2, 'Steelcase'), (3, 'Teknion'), (4, 'Haworth'), (5, 'Knoll'), (6, 'Wilkhahn'), (7, 'Benel'), (8, 'Fusys'), (9, 'Humanscale'), (10, 'Enjoy'), (11, 'Ergohuman'), (12, 'Artmatrix')], default=0)),
                ('桌面颜色', models.IntegerField(choices=[(1, 'Maple'), (2, 'White'), (3, 'Grey'), (4, 'Cherry'), (5, 'Brown'), (6, 'Beech'), (7, 'Ivory'), (8, 'Black')], default=1)),
                ('桌子形状', models.IntegerField(choices=[(0, 'L Shape Desk - Left Sided'), (1, 'L Shape Desk - Right Sided'), (2, 'Straight'), (3, 'P Shape'), (4, 'B Shape'), (5, 'Square'), (6, 'Oval'), (7, 'Boat Shape'), (8, 'Other'), (9, 'L Shape - Left OR Right')], default=3)),
                ('长', models.IntegerField(choices=[(400, '400'), (450, '450'), (500, '500'), (600, '600'), (650, '650'), (700, '700'), (750, '750'), (800, '800'), (850, '850'), (900, '900'), (1100, '1100'), (1200, '1200'), (1350, '1350'), (1400, '1400'), (1450, '1450'), (1500, '1500'), (1600, '1600'), (1650, '1650'), (1700, '1700'), (1800, '1800'), (2100, '2100'), (-1, 'Other Measurements')], default=1500)),
                ('其他长度', models.IntegerField(blank=True, null=True)),
                ('宽', models.IntegerField(choices=[(400, '400'), (450, '450'), (500, '500'), (600, '600'), (650, '650'), (700, '700'), (750, '750'), (800, '800'), (850, '850'), (900, '900'), (1100, '1100'), (1200, '1200'), (1350, '1350'), (1400, '1400'), (1450, '1450'), (1500, '1500'), (1600, '1600'), (1650, '1650'), (1700, '1700'), (1800, '1800'), (2100, '2100'), (-1, 'Other Measurements')], default=600)),
                ('其他宽度', models.IntegerField(blank=True, null=True)),
                ('厚', models.IntegerField(choices=[(1, '25mm'), (2, '30mm'), (3, 'Less than 25mm'), (4, 'Others')], default=1)),
                ('其他厚度', models.IntegerField(blank=True, null=True)),
                ('主桌深度', models.IntegerField(choices=[(400, '400'), (450, '450'), (500, '500'), (600, '600'), (650, '650'), (700, '700'), (750, '750'), (800, '800'), (850, '850'), (900, '900'), (1100, '1100'), (1200, '1200'), (1350, '1350'), (1400, '1400'), (1450, '1450'), (1500, '1500'), (1600, '1600'), (1650, '1650'), (1700, '1700'), (1800, '1800'), (2100, '2100'), (-1, 'Other Measurements')], default=600)),
                ('其他主桌深度', models.IntegerField(blank=True, null=True)),
                ('侧桌深度', models.IntegerField(choices=[(400, '400'), (450, '450'), (500, '500'), (600, '600'), (650, '650'), (700, '700'), (750, '750'), (800, '800'), (850, '850'), (900, '900'), (1100, '1100'), (1200, '1200'), (1350, '1350'), (1400, '1400'), (1450, '1450'), (1500, '1500'), (1600, '1600'), (1650, '1650'), (1700, '1700'), (1800, '1800'), (2100, '2100'), (-1, 'Other Measurements')], default=600)),
                ('其他侧桌深度', models.IntegerField(blank=True, null=True)),
                ('洞的数目', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('洞的形状', models.IntegerField(choices=[(1, 'Rectangular'), (2, 'Round'), (3, 'Flat'), (4, 'Others'), (5, 'Half Round')], default=2)),
                ('洞的位置', models.CharField(blank=True, default='', max_length=200)),
                ('是否有问题', models.BooleanField(default=False)),
                ('描述', models.TextField(blank=True, default='', max_length=500)),
                ('数量', models.IntegerField()),
                ('编号', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Desks',
            },
        ),
        migrations.CreateModel(
            name='Pedestal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_Code', models.IntegerField(choices=[(1, 'E9 Premium, #06-17'), (2, 'Hiangkie Industrial Building, #04-14'), (3, 'Mayfair Industrial Building, #05-30')], default=0)),
                ('Area_Code', models.IntegerField(default=0)),
                ('Image', models.CharField(default='', max_length=200)),
                ('Brand', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Herman Miller'), (2, 'Steelcase'), (3, 'Teknion'), (4, 'Haworth'), (5, 'Knoll'), (6, 'Wilkhahn'), (7, 'Benel'), (8, 'Fusys'), (9, 'Humanscale'), (10, 'Enjoy'), (11, 'Ergohuman'), (12, 'Artmatrix'), (13, 'X3'), (14, 'Unigroup')], default=0)),
                ('Color', models.IntegerField(choices=[(1, 'Maple'), (2, 'White'), (3, 'Grey'), (4, 'Cherry'), (5, 'Brown'), (6, 'Beech'), (7, 'Ivory'), (8, 'Black')], default=1)),
                ('Material', models.IntegerField(choices=[(1, 'Wooden'), (2, 'Metal')], default=1)),
                ('Drawer', models.IntegerField(choices=[(1, '2 Drawers'), (2, '2D1F'), (3, '3 Small Drawers')], default=1)),
                ('Height', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('Depth', models.IntegerField()),
                ('Wheel', models.IntegerField(choices=[(1, 'No wheels'), (2, '4 wheels'), (3, '5 wheels')], default=1)),
                ('Handle', models.IntegerField(choices=[(1, 'With handle'), (2, 'No Handle')], default=1)),
                ('Is_Faulty', models.BooleanField(default=False)),
                ('Description', models.TextField(default='', max_length=500)),
                ('Quantity_For_This_Entry', models.IntegerField()),
                ('Custom_Code', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Pedestals',
            },
        ),
    ]
